'use client';
import { FormEvent, useEffect, useState } from 'react';
import { api, type ProfessionalServiceRequest, type PublicBusinessProfile, type UploadedMediaAsset } from '../../lib/api-client';
import { ActionButton, ActionLink, EmptyState, PageHeader, PageShell, SkeletonGrid, StatusMessage, Surface } from '../components/ui-primitives';

function RequestImages({ id }: { id: string }) {
  const [images, setImages] = useState<UploadedMediaAsset[]>([]);
  useEffect(() => { void api.media.listForOwner('professional_request', id).then(setImages).catch(() => undefined); }, [id]);
  return images.length ? <div className="ui-page-actions">{images.map((image) => <img key={image.id} src={image.publicUrl} alt="صورة المشكلة" width={120} height={90} />)}</div> : null;
}

export default function Opportunities() {
  const [businesses, setBusinesses] = useState<PublicBusinessProfile[]>([]), [businessId, setBusinessId] = useState('');
  const [rows, setRows] = useState<ProfessionalServiceRequest[]>([]), [jobs, setJobs] = useState<ProfessionalServiceRequest[]>([]);
  const [loading, setLoading] = useState(true), [message, setMessage] = useState('');
  useEffect(() => { void api.businesses.listMine().then((r) => { setBusinesses(r.businesses); if (r.businesses[0]) setBusinessId(r.businesses[0].id); }).catch((c) => setMessage(c.message)).finally(() => setLoading(false)); }, []);
  function load() { if (!businessId) return; void Promise.all([api.professionalServices.opportunities(businessId), api.professionalServices.jobs(businessId)]).then(([o, j]) => { setRows(o.requests); setJobs(j.requests); }).catch((c) => setMessage(c.message)); }
  useEffect(load, [businessId]);
  async function offer(event: FormEvent<HTMLFormElement>, requestId: string) { event.preventDefault(); const f = new FormData(event.currentTarget); try { await api.professionalServices.offer(requestId, businessId, { inspectionFee: Number(f.get('inspectionFee') || 0), laborFee: Number(f.get('laborFee')), materialsFee: f.get('materialsFee') ? Number(f.get('materialsFee')) : undefined, currency: f.get('currency'), arrivalMinutes: Number(f.get('arrivalMinutes')), durationMinutes: Number(f.get('durationMinutes')), warrantyDays: Number(f.get('warrantyDays') || 0), scopeAr: f.get('scopeAr'), exclusionsAr: f.get('exclusionsAr') || undefined }); setRows((v) => v.filter((x) => x.id !== requestId)); setMessage('تم إرسال العرض للمستخدم.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'تعذر إرسال العرض.'); } }
  async function jobAction(id: string, action: 'start' | 'request_completion' | 'dispute') { const note = action === 'dispute' ? window.prompt('اشرح سبب النزاع') ?? undefined : undefined; try { await api.professionalServices.action(id, action, note); setMessage('تم تحديث حالة المهمة.'); load(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'تعذر التحديث.'); } }
  if (loading) return <PageShell label="فرص العمل"><SkeletonGrid count={3} /></PageShell>;
  return <PageShell label="فرص العمل"><PageHeader eyebrow="مساحة المهني" title="طلبات قريبة مطابقة لمهنتك" description="العنوان ورقم العميل مخفيان حتى قبول عرضك. قدّم سعرًا واضحًا وضمانًا واقعيًا." backHref="/business-profiles" actions={<ActionLink href="/professional-services">طلبات المستخدم</ActionLink>} />
    {message && <StatusMessage tone={message.startsWith('تم ') ? 'success' : 'danger'}>{message}</StatusMessage>}
    {businesses.length > 1 && <Surface><label>النشاط<select value={businessId} onChange={(e) => setBusinessId(e.target.value)}>{businesses.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label></Surface>}
    {jobs.length > 0 && <><h2>المهام المقبولة</h2><section className="ui-card-grid">{jobs.map((job) => <Surface as="article" key={job.id}><strong>{job.status}</strong><h3>{job.titleAr}</h3><p>{job.address} · <span dir="ltr">{job.customerPhone}</span></p><RequestImages id={job.id} /><div className="ui-page-actions">{job.status === 'offer_selected' && <ActionButton onClick={() => void jobAction(job.id, 'start')}>بدأت العمل</ActionButton>}{job.status === 'in_progress' && <ActionButton onClick={() => void jobAction(job.id, 'request_completion')}>طلب اعتماد الإنجاز</ActionButton>}{['in_progress', 'completion_pending'].includes(job.status) && <ActionButton variant="secondary" onClick={() => void jobAction(job.id, 'dispute')}>فتح نزاع</ActionButton>}</div></Surface>)}</section></>}
    {!businesses.length ? <EmptyState title="لا يوجد نشاط مهني" description="أنشئ نشاطًا واعتمده أولًا لاستقبال فرص العمل." actions={<ActionLink href="/business-profiles/new">إنشاء نشاط</ActionLink>} /> : rows.length ? <><h2>فرص جديدة</h2><section className="ui-card-grid">{rows.map((request) => <Surface as="article" key={request.id}><strong>{request.urgency === 'urgent' ? 'طارئ' : request.urgency === 'today' ? 'اليوم' : 'موعد محدد'}</strong><h2>{request.titleAr}</h2><p>{request.descriptionAr}</p><p>المنطقة التقريبية: {request.areaLabel}</p><RequestImages id={request.id} /><Surface as="form" className="ui-form" onSubmit={(e) => void offer(e, request.id)}><div className="ui-form-grid"><label>أجرة الكشف<input name="inspectionFee" type="number" min="0" defaultValue="0" /></label><label>أجرة العمل<input name="laborFee" type="number" min="0" required /></label><label>المواد التقديرية<input name="materialsFee" type="number" min="0" /></label><label>العملة<select name="currency" defaultValue={request.currency}><option>SYP</option><option>USD</option></select></label><label>الوصول بالدقائق<input name="arrivalMinutes" type="number" min="1" max="10080" required /></label><label>مدة العمل بالدقائق<input name="durationMinutes" type="number" min="1" required /></label><label>الضمان بالأيام<input name="warrantyDays" type="number" min="0" max="3650" defaultValue="0" /></label></div><label>ما الذي يشمله العرض؟<textarea name="scopeAr" minLength={10} maxLength={1200} required /></label><label>الاستثناءات<textarea name="exclusionsAr" maxLength={800} /></label><ActionButton type="submit">إرسال العرض</ActionButton></Surface></Surface>)}</section></> : <EmptyState title="لا توجد فرص مطابقة الآن" description="ستظهر هنا الطلبات المفتوحة المطابقة لتصنيف نشاطك المعتمد." />}
  </PageShell>;
}
