import { Inject, Injectable } from '@nestjs/common';
import { DatabasePool } from '../database/database.pool';
import type { ProfessionalOffer, ProfessionalRequest, RequestStatus } from './professional-service.types';
import { randomUUID } from 'node:crypto';
@Injectable()
export class ProfessionalServiceRepository{
 constructor(@Inject(DatabasePool) private readonly db:DatabasePool){}
 async create(r:ProfessionalRequest){await this.db.query(`INSERT INTO professional_service_requests(id,customer_user_id,category_code,title_ar,description_ar,urgency,scheduled_for,budget_min,budget_max,currency,address,area_label,latitude,longitude,customer_phone,status,expires_at,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'open',$16,$17,$17)`,[r.id,r.customerUserId,r.categoryCode,r.titleAr,r.descriptionAr,r.urgency,r.scheduledFor??null,r.budgetMin??null,r.budgetMax??null,r.currency,r.address,r.areaLabel,r.latitude,r.longitude,r.customerPhone,r.expiresAt,r.createdAt]);return r;}
 async find(id:string){const [r]=await this.db.query<any>(`SELECT * FROM professional_service_requests WHERE id=$1`,[id]);return r?mapRequest(r):undefined;}
 async mine(userId:string){return (await this.db.query<any>(`SELECT * FROM professional_service_requests WHERE customer_user_id=$1 ORDER BY created_at DESC`,[userId])).map(mapRequest);}
 async opportunities(businessId:string){return (await this.db.query<any>(`SELECT r.* FROM professional_service_requests r JOIN business_profiles b ON b.id=$1 WHERE r.status='open' AND r.expires_at>NOW() AND r.category_code=b.category_code AND b.visibility='public' AND b.moderation_status='approved' AND b.trust_status='approved' AND NOT EXISTS(SELECT 1 FROM professional_service_offers o WHERE o.request_id=r.id AND o.provider_business_id=b.id) ORDER BY CASE r.urgency WHEN 'urgent' THEN 0 WHEN 'today' THEN 1 ELSE 2 END,r.created_at`,[businessId])).map(mapRequest).map(({address,customerPhone,latitude,longitude,customerUserId,...safe})=>safe);}
 async offers(requestId:string){return (await this.db.query<any>(`SELECT o.*,b.name provider_name FROM professional_service_offers o JOIN business_profiles b ON b.id=o.provider_business_id WHERE o.request_id=$1 ORDER BY o.created_at`,[requestId])).map(mapOffer);}
  async addOffer(o:ProfessionalOffer,owner:string){return this.db.transaction(async c=>{const locked=await c.query(`SELECT id FROM professional_service_requests WHERE id=$1 AND status='open' AND expires_at>NOW() FOR UPDATE`,[o.requestId]);if(!locked.rows[0])return undefined;const count=await c.query<{count:string}>(`SELECT COUNT(*)::text count FROM professional_service_offers WHERE request_id=$1 AND status='submitted'`,[o.requestId]);if(Number(count.rows[0]?.count??0)>=5)return undefined;await c.query(`INSERT INTO professional_service_offers(id,request_id,provider_business_id,provider_owner_user_id,inspection_fee,labor_fee,materials_fee,currency,arrival_minutes,duration_minutes,warranty_days,scope_ar,exclusions_ar,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'submitted',$14,$14)`,[o.id,o.requestId,o.providerBusinessId,owner,o.inspectionFee,o.laborFee,o.materialsFee??null,o.currency,o.arrivalMinutes,o.durationMinutes,o.warrantyDays,o.scopeAr,o.exclusionsAr??null,o.createdAt]);return o;});}
  async offerCount(requestId:string){const [r]=await this.db.query<{count:string}>(`SELECT COUNT(*)::text count FROM professional_service_offers WHERE request_id=$1 AND status='submitted'`,[requestId]);return Number(r?.count??0);}
 async accept(requestId:string,offerId:string,userId:string){return this.db.transaction(async c=>{const q=await c.query<any>(`SELECT status,customer_user_id FROM professional_service_requests WHERE id=$1 FOR UPDATE`,[requestId]);if(!q.rows[0]||q.rows[0].customer_user_id!==userId||q.rows[0].status!=='open')return undefined;const offer=await c.query<any>(`SELECT * FROM professional_service_offers WHERE id=$1 AND request_id=$2 AND status='submitted'`,[offerId,requestId]);if(!offer.rows[0])return undefined;await c.query(`UPDATE professional_service_offers SET status=CASE WHEN id=$2 THEN 'accepted' ELSE 'rejected' END,updated_at=NOW() WHERE request_id=$1 AND status='submitted'`,[requestId,offerId]);await c.query(`UPDATE professional_service_requests SET status='offer_selected',accepted_offer_id=$2,updated_at=NOW() WHERE id=$1`,[requestId,offerId]);await c.query(`INSERT INTO professional_service_events(id,request_id,actor_user_id,from_status,to_status,occurred_at) VALUES(gen_random_uuid()::text,$1,$2,'open','offer_selected',NOW())`,[requestId,userId]);return mapOffer(offer.rows[0]);});}
  async transition(requestId:string,from:RequestStatus,to:RequestStatus,actor:string,note?:string){const rows=await this.db.query<any>(`UPDATE professional_service_requests SET status=$3,completed_at=CASE WHEN $3='completed' THEN NOW() ELSE completed_at END,payment_status=CASE WHEN $3='completed' THEN 'cash_collected' ELSE payment_status END,updated_at=NOW() WHERE id=$1 AND status=$2 RETURNING *`,[requestId,from,to]);if(!rows[0])return undefined;await this.db.query(`INSERT INTO professional_service_events(id,request_id,actor_user_id,from_status,to_status,note,occurred_at) VALUES($1,$2,$3,$4,$5,$6,NOW())`,[randomUUID(),requestId,actor,from,to,note??null]);return mapRequest(rows[0]);}
  async providerOwner(requestId:string){const [r]=await this.db.query<any>(`SELECT o.provider_owner_user_id,o.provider_business_id,o.warranty_days,o.scope_ar FROM professional_service_requests r JOIN professional_service_offers o ON o.id=r.accepted_offer_id WHERE r.id=$1`,[requestId]);return r;}
  async providerJobs(businessId:string){return (await this.db.query<any>(`SELECT r.* FROM professional_service_requests r JOIN professional_service_offers o ON o.id=r.accepted_offer_id WHERE o.provider_business_id=$1 AND r.status IN ('offer_selected','in_progress','completion_pending','completed','disputed') ORDER BY r.updated_at DESC`,[businessId])).map(mapRequest);}
  async warranty(requestId:string,providerId:string,days:number,terms:string){if(days<=0)return;await this.db.query(`INSERT INTO professional_service_warranties(id,request_id,provider_business_id,starts_at,ends_at,terms_ar,status) VALUES($1,$2,$3,NOW(),NOW()+($4||' days')::interval,$5,'active') ON CONFLICT(request_id) DO NOTHING`,[randomUUID(),requestId,providerId,days,terms]);}
  async requestRevisit(requestId:string,reason:string){const rows=await this.db.query(`UPDATE professional_service_warranties SET status='revisit_requested',revisit_reason=$2,updated_at=NOW() WHERE request_id=$1 AND status='active' AND ends_at>=NOW() RETURNING id`,[requestId,reason]);return !!rows[0];}
  async rate(requestId:string,userId:string,providerId:string,v:{quality:number;punctuality:number;priceAccuracy:number;conduct:number;comment?:string}){await this.db.query(`INSERT INTO professional_service_ratings(id,request_id,customer_user_id,provider_business_id,quality,punctuality,price_accuracy,conduct,comment) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[randomUUID(),requestId,userId,providerId,v.quality,v.punctuality,v.priceAccuracy,v.conduct,v.comment??null]);}
}
function mapRequest(r:any):ProfessionalRequest{return{id:r.id,customerUserId:r.customer_user_id,categoryCode:r.category_code,titleAr:r.title_ar,descriptionAr:r.description_ar,urgency:r.urgency,scheduledFor:r.scheduled_for?.toISOString(),budgetMin:r.budget_min==null?undefined:Number(r.budget_min),budgetMax:r.budget_max==null?undefined:Number(r.budget_max),currency:r.currency,address:r.address,areaLabel:r.area_label,latitude:Number(r.latitude),longitude:Number(r.longitude),customerPhone:r.customer_phone,status:r.status,acceptedOfferId:r.accepted_offer_id??undefined,paymentMethod:r.payment_method??'cash',paymentStatus:r.payment_status??'pending',expiresAt:r.expires_at.toISOString(),completedAt:r.completed_at?.toISOString(),createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()}}
function mapOffer(r:any):ProfessionalOffer{return{id:r.id,requestId:r.request_id,providerBusinessId:r.provider_business_id,providerName:r.provider_name,inspectionFee:Number(r.inspection_fee),laborFee:Number(r.labor_fee),materialsFee:r.materials_fee==null?undefined:Number(r.materials_fee),total:Number(r.inspection_fee)+Number(r.labor_fee)+Number(r.materials_fee??0),currency:r.currency,arrivalMinutes:r.arrival_minutes,durationMinutes:r.duration_minutes,warrantyDays:r.warranty_days,scopeAr:r.scope_ar,exclusionsAr:r.exclusions_ar??undefined,status:r.status,createdAt:r.created_at.toISOString()}}
