import { BadRequestException, ForbiddenException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { BusinessProfileRepository } from '../business-profiles/business-profile.repository';
import { CategoryService } from '../categories/category.service';
import { IdentityRepository } from '../identity/identity.repository';
import { IdentityService } from '../identity/identity.service';
import { readSessionToken } from '../identity/session-cookie';
import { ProfessionalServiceRepository } from './professional-service.repository';
import type { ProfessionalOffer, ProfessionalRequest, RequestStatus } from './professional-service.types';
import { validateAction, validateOffer, validateRequest } from './professional-service.validation';

@Injectable()
export class ProfessionalServiceService{
 constructor(@Inject(ProfessionalServiceRepository)private readonly repo:ProfessionalServiceRepository,@Inject(BusinessProfileRepository)private readonly businesses:BusinessProfileRepository,@Inject(CategoryService)private readonly categories:CategoryService,@Inject(IdentityService)private readonly identity:IdentityService,@Inject(IdentityRepository)private readonly audits:IdentityRepository){}
 private async actor(cookie?:string){return this.identity.getCurrentUser(readSessionToken(cookie));}
 async create(cookie:string|undefined,value:Record<string,unknown>){const actor=await this.actor(cookie),v=validateRequest(value);await this.categories.assertActiveCategory(v.categoryCode);const now=new Date(),r:ProfessionalRequest={id:randomUUID(),customerUserId:actor.id,...v,status:'open',expiresAt:new Date(now.getTime()+48*3600_000).toISOString(),createdAt:now.toISOString(),updatedAt:now.toISOString()};await this.repo.create(r);await this.audits.appendAuditLog('professional_request.created',{actorUserId:actor.id,correlationId:r.id});return r;}
 async mine(cookie?:string){const actor=await this.actor(cookie);const rows=await this.repo.mine(actor.id);return Promise.all(rows.map(async({customerUserId,...r})=>({...r,offers:await this.repo.offers(r.id)})));}
 async opportunities(cookie:string|undefined,businessId:string){const actor=await this.actor(cookie),b=await this.businesses.findById(businessId);if(!b||b.ownerUserId!==actor.id)throw new ForbiddenException('Access denied.');return this.repo.opportunities(businessId);}
 async jobs(cookie:string|undefined,businessId:string){const actor=await this.actor(cookie),b=await this.businesses.findById(businessId);if(!b||b.ownerUserId!==actor.id)throw new ForbiddenException('Access denied.');return (await this.repo.providerJobs(businessId)).map(({customerUserId,...r})=>r);}
 async offer(cookie:string|undefined,requestId:string,businessId:string,value:Record<string,unknown>){const actor=await this.actor(cookie),b=await this.businesses.findById(businessId),r=await this.repo.find(requestId);if(!b||b.ownerUserId!==actor.id)throw new ForbiddenException('Access denied.');if(!r||r.status!=='open'||new Date(r.expiresAt)<=new Date())throw new BadRequestException('Request is not open.');if(b.categoryCode!==r.categoryCode||b.visibility!=='public'||b.moderationStatus!=='approved'||b.trustStatus!=='approved')throw new ForbiddenException('Provider is not eligible for this request.');if(await this.repo.offerCount(requestId)>=5)throw new BadRequestException('This request already has five offers.');const v=validateOffer(value);if(v.currency!==r.currency)throw new BadRequestException('Offer currency must match request currency.');const o:ProfessionalOffer={id:randomUUID(),requestId,providerBusinessId:businessId,providerName:b.name,...v,total:v.inspectionFee+v.laborFee+(v.materialsFee??0),status:'submitted',createdAt:new Date().toISOString()};const saved=await this.repo.addOffer(o,actor.id);if(!saved)throw new BadRequestException('This request already has five offers or is no longer open.');return saved;}
 async accept(cookie:string|undefined,requestId:string,offerId:string){const actor=await this.actor(cookie),o=await this.repo.accept(requestId,offerId,actor.id);if(!o)throw new BadRequestException('Offer cannot be accepted.');await this.audits.appendAuditLog('professional_offer.accepted',{actorUserId:actor.id,correlationId:requestId});return o;}
 async action(cookie:string|undefined,requestId:string,value:Record<string,unknown>){const actor=await this.actor(cookie),r=await this.repo.find(requestId);if(!r)throw new NotFoundException('Request was not found.');const p=await this.repo.providerOwner(requestId),isCustomer=r.customerUserId===actor.id,isProvider=p?.provider_owner_user_id===actor.id,{action,note}=validateAction(value);let to:RequestStatus|undefined;
  if(action==='start'&&isProvider&&r.status==='offer_selected')to='in_progress';
  if(action==='request_completion'&&isProvider&&r.status==='in_progress')to='completion_pending';
  if(action==='confirm_completion'&&isCustomer&&r.status==='completion_pending')to='completed';
  if(action==='cancel'&&isCustomer&&['open','offer_selected'].includes(r.status))to='cancelled';
  if(action==='dispute'&&(isCustomer||isProvider)&&['in_progress','completion_pending'].includes(r.status))to='disputed';
  if(!to)throw new ForbiddenException('This transition is not allowed.');const updated=await this.repo.transition(requestId,r.status,to,actor.id,note);if(!updated)throw new BadRequestException('Request changed; refresh and retry.');if(to==='completed'&&p)await this.repo.warranty(requestId,p.provider_business_id,p.warranty_days,p.scope_ar);return updated;
 }
 async revisit(cookie:string|undefined,id:string,reasonValue:unknown){const actor=await this.actor(cookie),r=await this.repo.find(id);if(!r||r.customerUserId!==actor.id)throw new ForbiddenException('Access denied.');const reason=String(reasonValue??'').trim();if(reason.length<5||reason.length>1000)throw new BadRequestException('reason is invalid.');if(!await this.repo.requestRevisit(id,reason))throw new BadRequestException('No active warranty is available.');return{requested:true};}
 async rate(cookie:string|undefined,id:string,value:Record<string,unknown>){const actor=await this.actor(cookie),r=await this.repo.find(id),p=await this.repo.providerOwner(id);if(!r||r.customerUserId!==actor.id||r.status!=='completed'||!p)throw new ForbiddenException('Rating is unavailable.');const score=(k:string)=>{const n=value[k];if(!Number.isInteger(n)||Number(n)<1||Number(n)>5)throw new BadRequestException(`${k} is invalid.`);return Number(n)};const comment=value.comment===undefined?undefined:String(value.comment).trim();if(comment&&comment.length>800)throw new BadRequestException('comment is invalid.');await this.repo.rate(id,actor.id,p.provider_business_id,{quality:score('quality'),punctuality:score('punctuality'),priceAccuracy:score('priceAccuracy'),conduct:score('conduct'),comment});return{rated:true};}
}
