'use client';
import QRCode from 'qrcode';
import { FormEvent,useEffect,useState } from 'react';
import { useParams,useRouter } from 'next/navigation';
import { api,KhedmahPromotion } from '../../../../lib/api-client';
import { ActionButton,ActionLink,EmptyState,PageHeader,PageShell,SkeletonGrid,StatusMessage,Surface } from '../../../components/ui-primitives';
export default function BusinessPromotionsPage(){const{id}=useParams<{id:string}>(),router=useRouter(),[rows,setRows]=useState<KhedmahPromotion[]>([]),[businessName,setBusinessName]=useState(''),[code,setCode]=useState(''),[qr,setQr]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[redeemCode,setRedeemCode]=useState('');
 async function load(){setLoading(true);try{const[businesses,mine,c]=await Promise.all([api.businesses.listMine(),api.promotions.mine(),api.promotions.code(id)]);const b=businesses.businesses.find(x=>x.id===id);if(!b){router.replace('/business-profiles');return}setBusinessName(b.name);setRows(mine.promotions.filter(p=>p.businessProfileId===id));setCode(c.code);const target=`${window.location.origin}/promotions?code=${encodeURIComponent(c.code)}`;setQr(await QRCode.toDataURL(target,{width:360,margin:2,errorCorrectionLevel:'M',color:{dark:'#082f49',light:'#ffffff'}}))}catch(c){const e=c as Error&{statusCode?:number};if(e.statusCode===401)router.replace(`/auth/login?next=${encodeURIComponent(`/promotions/business/${id}`)}`);else setError('تعذر تحميل إدارة العروض.')}finally{setLoading(false)}}useEffect(()=>{void load()},[id]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setMessage('');const f=new FormData(e.currentTarget);try{const result=await api.promotions.create(id,{titleAr:f.get('titleAr'),descriptionAr:f.get('descriptionAr'),discountType:f.get('discountType'),originalPrice:Number(f.get('originalPrice')),discountValue:Number(f.get('discountValue')),currency:f.get('currency'),startsAt:new Date(String(f.get('startsAt'))).toISOString(),endsAt:new Date(String(f.get('endsAt'))).toISOString(),totalLimit:Number(f.get('totalLimit')),perUserLimit:Number(f.get('perUserLimit'))});setMessage(result.moderation.autoApproved?'تم اعتماد العرض ونشره تلقائيًا في الصفحة الحية.':'تم حفظ العرض وتحويله للمراجعة بسبب شروط المخاطر.');e.currentTarget.reset();await load()}catch(c){setError((c as Error).message||'تعذر إنشاء العرض. راجع البيانات.')}}
 async function redeem(e:FormEvent){e.preventDefault();setError('');setMessage('');try{const r=await api.promotions.redeem(id,redeemCode.trim().toUpperCase());setMessage(`تم اعتماد الخصم للرمز ${r.claim.redemptionCode} بنجاح.`);setRedeemCode('');await load()}catch(c){setError((c as Error).message||'الرمز غير صالح أو مستخدم أو منتهي.')}}
 async function deactivate(p:KhedmahPromotion){if(!confirm('إيقاف العرض وإخفاؤه من الصفحة الحية؟'))return;await api.promotions.deactivate(p.id);setMessage('تم إيقاف العرض وإخفاؤه من الصفحة الحية.');await load()}
 if(loading)return <PageShell><SkeletonGrid/></PageShell>;
 return <PageShell label="إدارة خصومات النشاط"><PageHeader eyebrow="لوحة صاحب النشاط" title={`خصومات وعروض ${businessName}`} description="أنشئ عروضًا حقيقية، اطبع رمز خدمة الثابت مرة واحدة، وتحقق من رموز العملاء عند نقطة البيع." actions={<><ActionLink href={`/business-profiles/${id}/manage`} variant="secondary">لوحة النشاط</ActionLink><ActionLink href="/live">الصفحة الحية</ActionLink></>}/>{error&&<StatusMessage tone="danger">{error}</StatusMessage>}{message&&<StatusMessage tone="success">{message}</StatusMessage>}
 <section className="ui-card-grid"><Surface><h2>رمز خدمة الثابت</h2><p>هذا الرمز يخص النشاط ولا يتغير عند تغيير العروض. اطبعه وضعه عند المحاسب.</p>{qr&&<img src={qr} width="360" height="360" alt={`رمز خصومات ${businessName}`} style={{maxWidth:'100%',height:'auto'}}/>}<strong dir="ltr">{code}</strong><div className="ui-page-actions"><ActionButton variant="secondary" onClick={()=>window.print()}>طباعة الرمز</ActionButton></div></Surface>
 <Surface as="form" className="ui-form" onSubmit={redeem}><h2>تحقق من رمز العميل</h2><label>رمز الاستفادة<input dir="ltr" value={redeemCode} onChange={e=>setRedeemCode(e.target.value.toUpperCase())} pattern="[A-Z2-9]{10}" maxLength={10} required/></label><ActionButton type="submit">اعتماد الخصم</ActionButton><small>لا يُقبل الرمز المنتهي أو المستخدم أو الصادر لنشاط آخر.</small></Surface></section>
 <Surface as="form" className="ui-form" onSubmit={create}><h2>إنشاء عرض جديد</h2><div className="ui-form-grid"><label>عنوان العرض<input name="titleAr" minLength={4} maxLength={120} required/></label><label>نوع الخصم<select name="discountType"><option value="percentage">نسبة مئوية</option><option value="fixed_amount">قيمة ثابتة</option></select></label><label>السعر الأصلي<input name="originalPrice" type="number" min="0.01" step="0.01" required/></label><label>قيمة الخصم<input name="discountValue" type="number" min="0.01" step="0.01" required/></label><label>العملة<select name="currency"><option>SYP</option><option>USD</option></select></label><label>إجمالي الرموز المتاحة<input name="totalLimit" type="number" min="1" max="100000" defaultValue="100" required/></label><label>الحد لكل مستخدم<input name="perUserLimit" type="number" min="1" max="5" defaultValue="1" required/></label><label>بداية العرض<input name="startsAt" type="datetime-local" required/></label><label>نهاية العرض<input name="endsAt" type="datetime-local" required/></label></div><label>وصف الشروط وما يشمله العرض<textarea name="descriptionAr" minLength={10} maxLength={1000} required/></label><ActionButton type="submit">حفظ ونشر عند المطابقة</ActionButton></Surface>
 <h2>العروض الحالية</h2>{rows.length?<section className="ui-card-grid">{rows.map(p=><Surface as="article" key={p.id}><span className="ui-eyebrow">{p.moderationStatus==='approved'?'منشور حيًا':p.moderationStatus==='pending'?'قيد المراجعة':'مرفوض'}</span><h3>{p.titleAr}</h3><p>{p.redeemedCount.toLocaleString('ar-SY-u-nu-latn')} استخدام من {p.totalLimit.toLocaleString('ar-SY-u-nu-latn')}</p><p>ينتهي {new Date(p.endsAt).toLocaleString('ar-SY-u-nu-latn')}</p>{p.rejectionReason&&<StatusMessage tone="danger">{p.rejectionReason}</StatusMessage>}{p.status==='active'&&<ActionButton variant="danger" onClick={()=>void deactivate(p)}>إيقاف العرض</ActionButton>}</Surface>)}</section>:<EmptyState title="لا توجد عروض" description="أنشئ أول عرض واضح المدة والسعر والحدود."/>}</PageShell>}
