import { Inject, Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { DatabasePool } from '../database/database.pool';
import { finalPrice } from './promotion.validation';
import type { Promotion,PromotionClaim } from './promotion.types';
const projection=`p.*,b.name business_name`;
@Injectable()
export class PromotionRepository{
 constructor(@Inject(DatabasePool)private readonly db:DatabasePool){}
 async codeForBusiness(businessId:string,code:string){return this.db.transaction(async c=>{await c.query(`INSERT INTO promotion_business_codes(business_profile_id,static_code) VALUES($1,$2) ON CONFLICT(business_profile_id) DO NOTHING`,[businessId,code]);const q=await c.query<{static_code:string}>(`SELECT static_code FROM promotion_business_codes WHERE business_profile_id=$1`,[businessId]);return q.rows[0]!.static_code;});}
 async resolveCode(code:string){const [r]=await this.db.query<{business_profile_id:string;business_name:string}>(`SELECT c.business_profile_id,b.name business_name FROM promotion_business_codes c JOIN business_profiles b ON b.id=c.business_profile_id WHERE c.static_code=$1 AND b.visibility='public' AND b.moderation_status='approved' AND b.trust_status='approved' AND b.status='active'`,[code]);return r?{businessProfileId:r.business_profile_id,businessName:r.business_name}:undefined;}
 async insert(p:Promotion,autoApproved:boolean){await this.db.transaction(async c=>{await c.query(`INSERT INTO promotions(id,business_profile_id,owner_user_id,title_ar,description_ar,discount_type,original_price,discount_value,currency,starts_at,ends_at,total_limit,per_user_limit,status,moderation_status,moderation_policy_version,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$17)`,[p.id,p.businessProfileId,p.ownerUserId,p.titleAr,p.descriptionAr,p.discountType,p.originalPrice,p.discountValue,p.currency,p.startsAt,p.endsAt,p.totalLimit,p.perUserLimit,p.status,p.moderationStatus,p.moderationPolicyVersion,p.createdAt]);await c.query(`INSERT INTO promotion_events(id,promotion_id,actor_user_id,event_type,metadata) VALUES($1,$2,$3,'created',$4::jsonb)`,[randomUUID(),p.id,p.ownerUserId,JSON.stringify({policy:p.moderationPolicyVersion})]);if(autoApproved)await c.query(`INSERT INTO promotion_events(id,promotion_id,actor_user_id,event_type,metadata) VALUES($1,$2,$3,'auto_approved',$4::jsonb)`,[randomUUID(),p.id,p.ownerUserId,JSON.stringify({policy:p.moderationPolicyVersion})]);});}
 async find(id:string){const[r]=await this.db.query<any>(`SELECT ${projection} FROM promotions p JOIN business_profiles b ON b.id=p.business_profile_id WHERE p.id=$1`,[id]);return r?mapPromotion(r):undefined;}
 async listMine(owner:string){return(await this.db.query<any>(`SELECT ${projection} FROM promotions p JOIN business_profiles b ON b.id=p.business_profile_id WHERE p.owner_user_id=$1 ORDER BY p.created_at DESC`,[owner])).map(mapPromotion);}
 async listPublic(filters:{businessId?:string;cityCode?:string;q?:string}){const clauses=[`p.status='active'`,`p.moderation_status='approved'`,`p.starts_at<=NOW()`,`p.ends_at>NOW()`,`p.redeemed_count<p.total_limit`,`b.visibility='public'`,`b.moderation_status='approved'`,`b.trust_status='approved'`,`b.status='active'`],params:unknown[]=[];if(filters.businessId){params.push(filters.businessId);clauses.push(`p.business_profile_id=$${params.length}`)}if(filters.cityCode){params.push(filters.cityCode);clauses.push(`b.city_code=$${params.length}`)}if(filters.q){params.push(`%${filters.q}%`);clauses.push(`(p.title_ar ILIKE $${params.length} OR p.description_ar ILIKE $${params.length} OR b.name ILIKE $${params.length})`)}return(await this.db.query<any>(`SELECT ${projection} FROM promotions p JOIN business_profiles b ON b.id=p.business_profile_id WHERE ${clauses.join(' AND ')} ORDER BY p.ends_at,p.created_at DESC`,params)).map(mapPromotion).map(publicPromotion);}
 async deactivate(id:string,owner:string){const rows=await this.db.query<any>(`UPDATE promotions SET status='inactive',updated_at=NOW() WHERE id=$1 AND owner_user_id=$2 RETURNING *`,[id,owner]);if(rows[0])await this.db.query(`INSERT INTO promotion_events(id,promotion_id,actor_user_id,event_type) VALUES($1,$2,$3,'deactivated')`,[randomUUID(),id,owner]);return rows[0];}
 async issueClaim(promotionId:string,userId:string,claimId:string,redemptionCode:string){return this.db.transaction(async c=>{const locked=await c.query<any>(`SELECT * FROM promotions WHERE id=$1 AND status='active' AND moderation_status='approved' AND starts_at<=NOW() AND ends_at>NOW() FOR UPDATE`,[promotionId]);const p=locked.rows[0];if(!p||p.redeemed_count>=p.total_limit)return undefined;const counts=await c.query<{user_count:string;total_count:string}>(`SELECT COUNT(*) FILTER (WHERE user_id=$2)::text user_count,COUNT(*)::text total_count FROM promotion_claims WHERE promotion_id=$1 AND (status='redeemed' OR (status='issued' AND expires_at>NOW()))`,[promotionId,userId]);if(Number(counts.rows[0]?.user_count??0)>=p.per_user_limit||Number(counts.rows[0]?.total_count??0)>=p.total_limit)return undefined;const expires=new Date(Math.min(new Date(p.ends_at).getTime(),Date.now()+24*3600000));const now=new Date();await c.query(`INSERT INTO promotion_claims(id,promotion_id,user_id,redemption_code,expires_at,created_at) VALUES($1,$2,$3,$4,$5,$6)`,[claimId,promotionId,userId,redemptionCode,expires,now]);await c.query(`INSERT INTO promotion_events(id,promotion_id,claim_id,actor_user_id,event_type) VALUES($1,$2,$3,$4,'claimed')`,[randomUUID(),promotionId,claimId,userId]);return{id:claimId,promotionId,userId,redemptionCode,status:'issued',expiresAt:expires.toISOString(),createdAt:now.toISOString()} as PromotionClaim;});}
 async listClaims(userId:string){return(await this.db.query<any>(`SELECT c.*,p.title_ar,b.name business_name FROM promotion_claims c JOIN promotions p ON p.id=c.promotion_id JOIN business_profiles b ON b.id=p.business_profile_id WHERE c.user_id=$1 ORDER BY c.created_at DESC`,[userId])).map(mapClaim);}
 async redeem(owner:string,businessId:string,code:string){return this.db.transaction(async c=>{const q=await c.query<any>(`SELECT c.*,p.business_profile_id,p.title_ar FROM promotion_claims c JOIN promotions p ON p.id=c.promotion_id WHERE c.redemption_code=$1 AND p.business_profile_id=$2 FOR UPDATE OF c,p`,[code,businessId]);const claim=q.rows[0];if(!claim||claim.status!=='issued'||new Date(claim.expires_at)<=new Date())return undefined;await c.query(`UPDATE promotion_claims SET status='redeemed',redeemed_at=NOW(),redeemed_by_user_id=$2 WHERE id=$1`,[claim.id,owner]);await c.query(`UPDATE promotions SET redeemed_count=redeemed_count+1,updated_at=NOW() WHERE id=$1 AND redeemed_count<total_limit`,[claim.promotion_id]);await c.query(`INSERT INTO promotion_events(id,promotion_id,claim_id,actor_user_id,event_type) VALUES($1,$2,$3,$4,'redeemed')`,[randomUUID(),claim.promotion_id,claim.id,owner]);return{...mapClaim({...claim,status:'redeemed',redeemed_at:new Date()}),titleAr:claim.title_ar};});}
 async pending(){return(await this.db.query<any>(`SELECT ${projection} FROM promotions p JOIN business_profiles b ON b.id=p.business_profile_id WHERE p.moderation_status='pending' ORDER BY p.created_at`,[])).map(mapPromotion);}
 async review(id:string,status:'approved'|'rejected',reason:string|undefined,actor:string){const[r]=await this.db.query<any>(`UPDATE promotions SET moderation_status=$2,rejection_reason=$3,updated_at=NOW() WHERE id=$1 AND moderation_status='pending' RETURNING *`,[id,status,status==='rejected'?reason:null]);if(r)await this.db.query(`INSERT INTO promotion_events(id,promotion_id,actor_user_id,event_type,metadata) VALUES($1,$2,$3,'reviewed',$4::jsonb)`,[randomUUID(),id,actor,JSON.stringify({status,reason})]);return r?mapPromotion(r):undefined;}
}
function mapPromotion(r:any):Promotion{return{id:r.id,businessProfileId:r.business_profile_id,businessName:r.business_name,ownerUserId:r.owner_user_id,titleAr:r.title_ar,descriptionAr:r.description_ar,discountType:r.discount_type,originalPrice:Number(r.original_price),discountValue:Number(r.discount_value),finalPrice:finalPrice(r.discount_type,Number(r.original_price),Number(r.discount_value)),currency:r.currency,startsAt:new Date(r.starts_at).toISOString(),endsAt:new Date(r.ends_at).toISOString(),totalLimit:r.total_limit,perUserLimit:r.per_user_limit,redeemedCount:r.redeemed_count,status:r.status,moderationStatus:r.moderation_status,moderationPolicyVersion:r.moderation_policy_version??undefined,rejectionReason:r.rejection_reason??undefined,createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()}}
function publicPromotion(p:Promotion){const{ownerUserId:_,rejectionReason:__,...safe}=p;return safe;}
function mapClaim(r:any):PromotionClaim{return{id:r.id,promotionId:r.promotion_id,titleAr:r.title_ar,businessName:r.business_name,userId:r.user_id,redemptionCode:r.redemption_code,status:new Date(r.expires_at)<=new Date()&&r.status==='issued'?'expired':r.status,expiresAt:new Date(r.expires_at).toISOString(),redeemedAt:r.redeemed_at?new Date(r.redeemed_at).toISOString():undefined,createdAt:new Date(r.created_at).toISOString()}}
