import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');

test('cash fulfillment schema preserves money, pharmacy, rating and tracking boundaries',async()=>{const sql=await read('backend/migrations/versions/026_cash_fulfillment_orders.sql');for(const contract of [/payment_method = 'cash'/,/total = subtotal \+ delivery_fee/,/controlled_item/,/pharmacy_review_status/,/fulfillment_order_ratings_target_unique/,/score BETWEEN 1 AND 5/,/fulfillment_order_location_updates/,/fulfillment_order_location_order_unique/,/fulfillment_orders_customer_idempotency_unique/])assert.match(sql,contract);assert.doesNotMatch(sql,/card_number|payment_token|stripe|paypal/i);});

test('order service restricts actors, medicines and lifecycle transitions',async()=>{const service=await read('apps/backend/src/orders/order.service.ts');for(const contract of [/Controlled pharmacy items cannot be ordered/,/Pharmacist approval is required/,/Only the order customer can rate it/,/Ratings are available only after delivery/,/Only the assigned courier can share location/,/Location sharing is not active/])assert.match(service,contract);});

test('customer merchant and courier surfaces expose the complete cash journey',async()=>{const[customer,checkout,merchant,courier,alerts,product,restaurants,store]=await Promise.all([read('apps/frontend/app/orders/page.tsx'),read('apps/frontend/app/orders/checkout/page.tsx'),read('apps/frontend/app/orders/merchant/page.tsx'),read('apps/frontend/app/orders/courier/page.tsx'),read('apps/frontend/app/orders/order-alerts.ts'),read('apps/frontend/app/store/products/[id]/page.tsx'),read('apps/frontend/app/restaurants/page.tsx'),read('apps/frontend/app/store/page.tsx')]);assert.match(product,/اطلب الآن — الدفع نقدي/);assert.match(checkout,/رسوم التوصيل/);assert.match(checkout,/requestOrderNotifications/);assert.match(customer,/تقييم المنشأة/);assert.match(customer,/تقييم المندوب/);assert.match(customer,/customerNotice/);assert.match(merchant,/تعيين المندوب/);assert.match(merchant,/طلب جديد من زبون/);assert.match(merchant,/فعّل رنة الطلبات الجديدة/);assert.match(courier,/تم التسليم وتحصيل النقد/);assert.match(courier,/CourierLocationButton/);assert.match(courier,/شرح مهام مندوب التوصيل/);assert.match(courier,/فعّل رنة المهام الجديدة/);assert.match(alerts,/AudioContext/);assert.match(restaurants,/href="\/orders\/courier"/);assert.doesNotMatch(store,/href="\/orders\/courier"/);});

test('order polling and courier updates use the shared persistent rate limiter',async()=>{const app=await read('apps/backend/src/app.ts');const repository=await read('apps/backend/src/orders/order.repository.ts');assert.match(app,/\/api\/v1\/orders/);assert.match(repository,/ON CONFLICT \(order_id\) DO UPDATE/);});

test('courier handoff exposes both endpoints and safely releases declined work',async()=>{const[repository,service,types,client,courier,customer]=await Promise.all([read('apps/backend/src/orders/order.repository.ts'),read('apps/backend/src/orders/order.service.ts'),read('apps/backend/src/orders/order.types.ts'),read('apps/frontend/lib/api-client.ts'),read('apps/frontend/app/orders/courier/page.tsx'),read('apps/frontend/app/orders/page.tsx')]);assert.match(repository,/merchant\.address_ar AS pickup_address/);assert.match(repository,/merchant\.phone AS merchant_phone/);assert.match(repository,/courier\.phone AS courier_phone/);assert.match(repository,/WHEN \$9::boolean THEN NULL/);assert.match(service,/clearCourierBusinessId: true/);for(const source of[types,client])for(const field of['pickupAddress','merchantPhone','courierPhone'])assert.match(source,new RegExp(field));for(const label of['عنوان الاستلام','رقم المنشأة','عنوان التسليم','رقم العميل','محتوى الطلب'])assert.match(courier,new RegExp(label));assert.match(courier,/الطلب جاهز للاستلام/);assert.match(courier,/هل استلمت الطلب كاملًا فعليًا/);assert.match(courier,/هل سلّمت الطلب للعميل وحصّلت كامل المبلغ/);assert.match(customer,/رقم المندوب/);});

test('courier privacy eligibility and reassignment fail closed across the active lifecycle',async()=>{const[service,courier,location,map,catalog]=await Promise.all([read('apps/backend/src/orders/order.service.ts'),read('apps/frontend/app/orders/courier/page.tsx'),read('apps/frontend/app/orders/courier-location-button.tsx'),read('apps/frontend/app/map/page.tsx'),read('apps/frontend/app/components/category-directory.tsx')]);assert.equal((service.match(/await this\.assertCourierEligible\(o\.courierBusinessId\)/g)||[]).length,2);assert.match(service,/viewer !== "merchant"[\s\S]*delete safe\.customerPhone/);assert.match(service,/!accepted \|\| viewer === "merchant"[\s\S]*delete safe\.courierPhone/);assert.match(service,/\["courier_accepted", "ready_for_pickup", "picked_up"\]\.includes\(order\.status\)[\s\S]*latestLocation/);assert.match(courier,/knownOrderStatusesRef\.current = new Map\(incoming\.map/);assert.match(location,/if\(!navigator\.geolocation\)/);assert.match(map,/setProviders\(\[\]\)/);assert.match(map,/if \(!navigator\.geolocation\)/);assert.match(catalog,/history\.pushState/);assert.match(catalog,/addEventListener\('popstate'/);});
