import { AUDIT_EVENT_NAME_PATTERN } from './audit-types.mjs';

export const AuditEvent = Object.freeze({
  USER_ACCOUNT_CREATED: 'USER_ACCOUNT_CREATED',
  USER_ACCOUNT_UPDATED: 'USER_ACCOUNT_UPDATED',
  USER_ACCOUNT_STATUS_CHANGED: 'USER_ACCOUNT_STATUS_CHANGED',
  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  BUSINESS_PROFILE_CREATED: 'BUSINESS_PROFILE_CREATED',
  PROFESSIONAL_PROFILE_CREATED: 'PROFESSIONAL_PROFILE_CREATED',
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  SERVICE_CREATED: 'SERVICE_CREATED',
  LOCATION_CREATED: 'LOCATION_CREATED',
  TRUST_CREATED: 'TRUST_CREATED',
  RELATIONSHIP_CREATED: 'RELATIONSHIP_CREATED',
});

export function isAuditEventName(value) {
  return Object.values(AuditEvent).includes(value) && AUDIT_EVENT_NAME_PATTERN.test(value);
}
