'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, type AdminUserSummary } from '../../../lib/api-client';

const statusLabel=(status:string)=>({active:'نشط',suspended:'معلّق',pending:'بانتظار التحقق',archived:'مؤرشف',created:'جديد'}[status]??status);

export default function AdminUsersPage(){
  const router=useRouter();const [users,setUsers]=useState<AdminUserSummary[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [acting,setActing]=useState('');
  const load=async(term='')=>{setLoading(true);try{const result=await api.operationsProduct.users(term);setUsers(result.users);setError('')}catch(cause){const status=cause instanceof Error?(cause as Error&{statusCode?:number}).statusCode:undefined;if(status===401)return router.replace('/auth/login?next=%2Fadmin%2Fusers');setError(status===403?'هذا الحساب لا يملك صلاحية إدارة المستخدمين.':cause instanceof Error?cause.message:'تعذر تحميل المستخدمين.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const search=(event:FormEvent)=>{event.preventDefault();void load(query)};
  const change=async(user:AdminUserSummary)=>{const next=user.status==='active'?'suspended':'active';const reason=prompt(next==='suspended'?'اكتب سبب تعليق الحساب (5 أحرف على الأقل):':'اكتب سبب إعادة تفعيل الحساب (5 أحرف على الأقل):');if(!reason||reason.trim().length<5)return;if(!confirm(next==='suspended'?'سيتم تعليق الحساب وإبطال جلساته النشطة. هل تتابع؟':'هل تريد إعادة تفعيل هذا الحساب؟'))return;setActing(user.id);try{await api.operationsProduct.changeUserStatus(user.id,next,reason.trim());await load(query)}catch(cause){alert(cause instanceof Error?cause.message:'تعذر تحديث حالة الحساب.')}finally{setActing('')}};
  return <main id="foundation-content" className="operations-shell" dir="rtl"><header className="operations-header"><div><p className="eyebrow">خدمة · إدارة الهوية</p><h1>إدارة المستخدمين</h1><p>بحث محدود البيانات وتعليق أو إعادة تفعيل مسجل بالكامل. الحسابات الإدارية محمية من هذا المسار.</p></div><span className="status-badge">{users.length} نتيجة</span></header><nav className="admin-navigation"><Link href="/admin">لوحة الإدارة</Link><Link href="/admin/moderation">المراجعة والبلاغات</Link><Link href="/admin/smart-report">التقرير الذكي</Link></nav><section className="operations-panel"><form className="filter-bar" onSubmit={search}><label>ابحث بالاسم أو البريد<input value={query} onChange={(event)=>setQuery(event.target.value)} maxLength={100} placeholder="اسم المستخدم أو البريد الإلكتروني"/></label><button type="submit" disabled={loading}>بحث</button></form>{loading?<p aria-busy="true">جاري تحميل المستخدمين…</p>:error?<p className="form-error" role="alert">{error}</p>:users.length===0?<p>لا توجد حسابات مطابقة.</p>:<div className="moderation-list">{users.map(user=><article className="moderation-card" key={user.id}><div><h2>{user.displayName}</h2><p><bdi>{user.email}</bdi> · {statusLabel(user.status)}</p><small>انضم في {new Date(user.createdAt).toLocaleDateString('ar-SY')} · <bdi>{user.id}</bdi></small></div><div className="moderation-actions">{user.isAdmin?<span className="status-badge">حساب إداري محمي</span>:user.status==='active'||user.status==='suspended'?<button disabled={acting===user.id} className={user.status==='active'?'moderation-reject':'moderation-approve'} onClick={()=>void change(user)}>{user.status==='active'?'تعليق الحساب':'إعادة التفعيل'}</button>:<span>{statusLabel(user.status)}</span>}</div></article>)}</div>}</section></main>;
}
