'use client';
import { FormEvent,useEffect,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { api,KhedmahPromotion } from '../../lib/api-client';
import { ActionButton,ActionLink,EmptyState,PageHeader,PageShell,SkeletonGrid,StatusMessage,Surface } from '../components/ui-primitives';
import { PlatformIcon } from '../components/platform-icon';
import { PromotionCard } from './promotion-card';
import { PromotionScanner } from './promotion-scanner';
import styles from './promotions.module.css';
export default function PromotionsPage(){const params=useSearchParams(),code=params.get('code'),[rows,setRows]=useState<KhedmahPromotion[]>([]),[business,setBusiness]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState('');
 async function load(query=''){setLoading(true);setError('');try{if(code){const r=await api.promotions.scan(code);setRows(r.promotions);setBusiness(r.businessName)}else{const r=await api.promotions.list({q:query||undefined});setRows(r.promotions);setBusiness('')}}catch(c){setRows([]);setError((c as Error).message||'تعذر تحميل العروض.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[code]);function search(e:FormEvent){e.preventDefault();void load(q.trim())}function clear(){setQ('');void load('')}
 return <PageShell className={styles.page} label="خصومات وعروض خدمة"><PageHeader eyebrow="وفّر تحت مظلة خدمة" title={business?`عروض ${business}`:'خصومات وعروض خدمة'} description="اكتشف عروض الأنشطة المعتمدة، واحفظ رمز الاستفادة قبل انتهاء المدة أو نفاد العدد." actions={<><ActionLink href="/promotions/my" variant="secondary"><PlatformIcon name="tag" size={17}/>رموزي</ActionLink><ActionLink href="/business-profiles" variant="secondary"><PlatformIcon name="storefront" size={17}/>أضف عرضًا لنشاطك</ActionLink></>}/><Surface as="form" onSubmit={search} className={styles.searchForm}><label><span>ابحث في العروض</span><span className={styles.searchControl}><PlatformIcon name="search" size={20}/><input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="مطعم، صيانة، متجر…"/></span></label><div className={styles.searchActions}><ActionButton type="submit" disabled={loading}><PlatformIcon name="search" size={18}/>{loading?'جاري البحث…':'بحث'}</ActionButton>{q&&<ActionButton type="button" variant="secondary" onClick={clear}><PlatformIcon name="refresh" size={18}/>مسح</ActionButton>}</div></Surface>{!code&&<PromotionScanner/>}{error&&<StatusMessage tone="danger">{error}</StatusMessage>}{loading?<SkeletonGrid/>:rows.length?<section className="ui-card-grid">{rows.map(p=><PromotionCard key={p.id} promotion={p}/>)}</section>:<EmptyState icon={<PlatformIcon name="tag" size={32}/>} title={code?'لا يوجد عرض نشط لهذا النشاط':'لا توجد عروض مطابقة الآن'} description={code?'النشاط معتمد، لكن عروضه منتهية أو لم يبدأ نشرها بعد.':'جرّب مسح البحث، أو استكشف الأنشطة القريبة، أو أضف عرضًا لنشاطك.'} actions={<>{q&&<ActionButton type="button" variant="secondary" onClick={clear}>عرض كل العروض</ActionButton>}<ActionLink href="/map" variant="secondary">استكشف القريب منك</ActionLink><ActionLink href="/business-profiles">أضف عرضًا لنشاطك</ActionLink></>}/>}</PageShell>}
