'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, type ProfessionalServiceRequest } from '../../lib/api-client';
import { ActionButton, ActionLink, EmptyState, PageHeader, PageShell, SkeletonGrid, StatusMessage, Surface } from '../components/ui-primitives';
const labels:Record<ProfessionalServiceRequest['status'],string>={open:'بانتظار العروض',offer_selected:'تم اختيار مهني',in_progress:'العمل جارٍ',completion_pending:'بانتظار اعتماد الإنجاز',completed:'مكتمل والضمان محسوب',cancelled:'ملغي',disputed:'نزاع قيد المراجعة'};
export default function ProfessionalRequests(){
 const router=useRouter(),[rows,setRows]=useState<ProfessionalServiceRequest[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=()=>api.professionalServices.mine().then(r=>setRows(r.requests)).catch(c=>{if((c as {statusCode?:number}).statusCode===401)router.replace('/auth/login?next=%2Fprofessional-services');else setMessage(c instanceof Error?c.message:'تعذر التحميل.');}).finally(()=>setLoading(false));
 useEffect(()=>{void load()},[]);
 async function accept(id:string,offerId:string){try{await api.professionalServices.accept(id,offerId);setMessage('تم قبول العرض وإغلاق بقية العروض.');await load()}catch(c){setMessage(c instanceof Error?c.message:'تعذر قبول العرض.')}}
 async function action(id:string,a:'confirm_completion'|'cancel'|'dispute'){const note=a==='dispute'?window.prompt('اشرح سبب النزاع')??undefined:undefined;try{await api.professionalServices.action(id,a,note);await load()}catch(c){setMessage(c instanceof Error?c.message:'تعذر تحديث الطلب.')}}
 async function rate(id:string){const raw=window.prompt('قيّم الخدمة من 1 إلى 5');if(!raw)return;const score=Number(raw),comment=window.prompt('تعليق اختياري')??undefined;try{await api.professionalServices.rate(id,{quality:score,punctuality:score,priceAccuracy:score,conduct:score,comment});setMessage('تم حفظ التقييم.')}catch(c){setMessage(c instanceof Error?c.message:'تعذر حفظ التقييم.')}}
 if(loading)return <PageShell label="طلباتي المهنية"><SkeletonGrid count={3}/></PageShell>;
 return <PageShell label="طلباتي المهنية"><PageHeader eyebrow="من المشكلة إلى الضمان" title="طلبات الخدمات المهنية" description="قارن العروض، اختر المهني، وتابع التنفيذ والدفع النقدي والضمان من سجل واحد." backHref="/" actions={<ActionLink href="/professional-services/new">اطلب مهنيًا</ActionLink>}/>{message&&<StatusMessage tone={message.startsWith('تم ')?'success':'danger'}>{message}</StatusMessage>}{rows.length?<section className="ui-card-grid">{rows.map(r=><Surface as="article" key={r.id}><strong>{labels[r.status]}</strong><h2>{r.titleAr}</h2><p>{r.descriptionAr}</p><p>المنطقة: {r.areaLabel} · العروض: {r.offers?.length??0} من 5</p>{r.paymentStatus==='cash_collected'&&<p>تم تأكيد التحصيل النقدي عند اعتماد الإنجاز.</p>}{r.offers?.map(o=><Surface as="div" key={o.id}><h3>{o.providerName}</h3><p><strong>{o.total.toLocaleString('ar-SY-u-nu-latn')} {o.currency}</strong> · وصول خلال {o.arrivalMinutes} دقيقة · ضمان {o.warrantyDays} يومًا</p><p>{o.scopeAr}</p>{r.status==='open'&&o.status==='submitted'&&<ActionButton onClick={()=>void accept(r.id,o.id)}>قبول هذا العرض</ActionButton>}</Surface>)}<div className="ui-page-actions">{r.status==='open'&&<ActionButton variant="secondary" onClick={()=>void action(r.id,'cancel')}>إلغاء الطلب</ActionButton>}{r.status==='completion_pending'&&<ActionButton onClick={()=>void action(r.id,'confirm_completion')}>اعتماد الإنجاز والدفع النقدي</ActionButton>}{['in_progress','completion_pending'].includes(r.status)&&<ActionButton variant="secondary" onClick={()=>void action(r.id,'dispute')}>فتح نزاع</ActionButton>}{r.status==='completed'&&<><ActionButton onClick={()=>void rate(r.id)}>تقييم المهني</ActionButton><ActionButton variant="secondary" onClick={()=>{const reason=window.prompt('اشرح المشكلة التي ظهرت خلال الضمان');if(reason)void api.professionalServices.revisit(r.id,reason).then(()=>setMessage('تم إرسال طلب إعادة الإصلاح.')).catch(c=>setMessage(c.message))}}>طلب إعادة إصلاح</ActionButton></>}</div></Surface>)}</section>:<EmptyState title="لا توجد طلبات مهنية" description="اشرح المشكلة وأرسلها إلى المهنيين المعتمدين القريبين." actions={<ActionLink href="/professional-services/new">إنشاء أول طلب</ActionLink>}/>}</PageShell>;
}
