'use client';
import { FormEvent,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { api,type Category } from '../../../lib/api-client';
import { ActionButton,ActionLink,PageHeader,PageShell,StatusMessage,Surface } from '../../components/ui-primitives';
const read=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]??'');r.onerror=()=>reject(r.error);r.readAsDataURL(file)});
export default function NewProfessionalRequest(){const router=useRouter(),[categories,setCategories]=useState<Category[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[coords,setCoords]=useState<{latitude:number;longitude:number}>();
 useEffect(()=>{void api.categories.list().then(r=>setCategories(r.categories.filter(c=>!!c.parentCode)));},[]);
 function locate(){navigator.geolocation?.getCurrentPosition(p=>setCoords({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>setError('تعذر تحديد الموقع. أدخل الموقع لاحقًا أو اسمح للمتصفح بالوصول إليه.'));}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!coords){setError('يجب تحديد موقع المشكلة بدقة.');return}setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const {request}=await api.professionalServices.create({categoryCode:f.get('categoryCode'),titleAr:f.get('titleAr'),descriptionAr:f.get('descriptionAr'),urgency:f.get('urgency'),scheduledFor:f.get('urgency')==='scheduled'?f.get('scheduledFor'):undefined,budgetMin:f.get('budgetMin')?Number(f.get('budgetMin')):undefined,budgetMax:f.get('budgetMax')?Number(f.get('budgetMax')):undefined,currency:f.get('currency'),address:f.get('address'),areaLabel:f.get('areaLabel'),customerPhone:f.get('customerPhone'),...coords});const files=(f.getAll('images') as File[]).filter(x=>x.size);for(const [sortOrder,file]of files.slice(0,5).entries()){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('الصور المقبولة JPG وPNG وWebP وبحد 5 ميغابايت للصورة.');await api.media.uploadProblem(request.id,{filename:file.name,mimeType:file.type as 'image/jpeg',sizeBytes:file.size,content:await read(file),sortOrder});}router.push('/professional-services');}catch(c){setError(c instanceof Error?c.message:'تعذر إنشاء الطلب.');setBusy(false)}}
 return <PageShell label="اطلب مهنيًا"><PageHeader eyebrow="عروض من مهنيين موثوقين" title="اشرح المشكلة مرة واحدة" description="أرسل الوصف والصور والموقع، ثم قارن حتى خمسة عروض قبل اختيار المهني." backHref="/professional-services"/>{error&&<StatusMessage tone="danger">{error}</StatusMessage>}<Surface as="form" className="ui-form" onSubmit={submit}><label>المهنة<select name="categoryCode" required><option value="">اختر المهنة</option>{categories.map(c=><option key={c.code} value={c.code}>{c.nameAr}</option>)}</select></label><label>عنوان مختصر<input name="titleAr" minLength={4} maxLength={160} required placeholder="مثال: تسرب مياه تحت المغسلة"/></label><label>اشرح المشكلة<textarea name="descriptionAr" minLength={10} maxLength={2000} rows={5} required/></label><label>صور المشكلة — حتى 5 صور<input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple/></label><label>الأولوية<select name="urgency"><option value="urgent">طارئة</option><option value="today">اليوم</option><option value="scheduled">موعد محدد</option></select></label><label>الموعد عند اختياره<input name="scheduledFor" type="datetime-local"/></label><div className="ui-form-grid"><label>ميزانية من<input name="budgetMin" type="number" min="0"/></label><label>إلى<input name="budgetMax" type="number" min="0"/></label><label>العملة<select name="currency"><option>SYP</option><option>USD</option></select></label></div><label>المنطقة العامة<input name="areaLabel" required placeholder="مثال: دمشق — المزة"/></label><label>العنوان التفصيلي — لا يظهر قبل قبول العرض<input name="address" minLength={5} maxLength={300} required/></label><label>رقم التواصل — يبقى مخفيًا قبل القبول<input name="customerPhone" minLength={6} maxLength={30} required dir="ltr"/></label><div className="ui-page-actions"><ActionButton type="button" variant="secondary" onClick={locate}>{coords?'تم تحديد الموقع ✓':'تحديد موقعي'}</ActionButton><ActionButton type="submit" disabled={busy}>{busy?'جارٍ إنشاء الطلب…':'إرسال للمهنيين'}</ActionButton><ActionLink href="/professional-services" variant="quiet">إلغاء</ActionLink></div></Surface></PageShell>}
