#!/usr/bin/env bash
set -euo pipefail
: "${GOOGLE_CLOUD_PROJECT:?GOOGLE_CLOUD_PROJECT is required}"
: "${GOOGLE_CLOUD_REGION:?GOOGLE_CLOUD_REGION is required}"
: "${OPERATIONS_DEPLOYER_SERVICE_ACCOUNT:?OPERATIONS_DEPLOYER_SERVICE_ACCOUNT is required}"
: "${OPERATIONS_ARTIFACT_REPOSITORY:?OPERATIONS_ARTIFACT_REPOSITORY is required}"
: "${OPERATIONS_BACKEND_SERVICE:?OPERATIONS_BACKEND_SERVICE is required}"
: "${OPERATIONS_FRONTEND_SERVICE:?OPERATIONS_FRONTEND_SERVICE is required}"
: "${OPERATIONS_RUNTIME_SERVICE_ACCOUNT:?OPERATIONS_RUNTIME_SERVICE_ACCOUNT is required}"
npm run validate:google
node scripts/validate-operations-readiness.mjs --production
gcloud builds submit --project "$GOOGLE_CLOUD_PROJECT" --region "$GOOGLE_CLOUD_REGION" --service-account "$OPERATIONS_DEPLOYER_SERVICE_ACCOUNT" --config cloudbuild.production.yaml --substitutions="_REGION=${GOOGLE_CLOUD_REGION},_AR_REPOSITORY=${OPERATIONS_ARTIFACT_REPOSITORY},_BACKEND_SERVICE=${OPERATIONS_BACKEND_SERVICE},_FRONTEND_SERVICE=${OPERATIONS_FRONTEND_SERVICE},_RUNTIME_SERVICE_ACCOUNT=${OPERATIONS_RUNTIME_SERVICE_ACCOUNT}" .
