#!/usr/bin/env bash
set -euo pipefail
: "${GOOGLE_CLOUD_PROJECT:?GOOGLE_CLOUD_PROJECT is required}"
: "${GOOGLE_CLOUD_REGION:?GOOGLE_CLOUD_REGION is required}"
: "${OPERATIONS_DEPLOYER_SERVICE_ACCOUNT:?OPERATIONS_DEPLOYER_SERVICE_ACCOUNT is required}"
: "${OPERATIONS_ARTIFACT_REPOSITORY:?OPERATIONS_ARTIFACT_REPOSITORY is required}"
: "${OPERATIONS_BACKEND_SERVICE:?OPERATIONS_BACKEND_SERVICE is required}"
: "${OPERATIONS_FRONTEND_SERVICE:?OPERATIONS_FRONTEND_SERVICE is required}"
: "${OPERATIONS_RUNTIME_SERVICE_ACCOUNT:?OPERATIONS_RUNTIME_SERVICE_ACCOUNT is required}"
: "${NEXT_PUBLIC_FIREBASE_API_KEY:?NEXT_PUBLIC_FIREBASE_API_KEY is required}"
: "${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:?NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN is required}"
: "${NEXT_PUBLIC_FIREBASE_PROJECT_ID:?NEXT_PUBLIC_FIREBASE_PROJECT_ID is required}"
: "${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:?NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET is required}"
: "${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:?NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID is required}"
: "${NEXT_PUBLIC_FIREBASE_APP_ID:?NEXT_PUBLIC_FIREBASE_APP_ID is required}"
: "${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:?NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID is required}"
IMAGE_TAG="${IMAGE_TAG:-manual-$(date -u +%Y%m%d%H%M%S)}"
COMMIT_SHA="$(git rev-parse HEAD)"
npm run validate:google
node scripts/validate-operations-readiness.mjs --production
gcloud builds submit --project "$GOOGLE_CLOUD_PROJECT" --region "$GOOGLE_CLOUD_REGION" --service-account "$OPERATIONS_DEPLOYER_SERVICE_ACCOUNT" --config cloudbuild.production.yaml --substitutions="_REGION=${GOOGLE_CLOUD_REGION},_AR_REPOSITORY=${OPERATIONS_ARTIFACT_REPOSITORY},_BACKEND_SERVICE=${OPERATIONS_BACKEND_SERVICE},_FRONTEND_SERVICE=${OPERATIONS_FRONTEND_SERVICE},_RUNTIME_SERVICE_ACCOUNT=${OPERATIONS_RUNTIME_SERVICE_ACCOUNT},_OPERATIONS_PRODUCT_ROLE_BINDINGS=${OPERATIONS_PRODUCT_ROLE_BINDINGS},COMMIT_SHA=${COMMIT_SHA}" .
