export const OrganizationAuditEvent = Object.freeze({
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  ORGANIZATION_STATUS_CHANGED: 'ORGANIZATION_STATUS_CHANGED',
  ORGANIZATION_ARCHIVED: 'ORGANIZATION_ARCHIVED',
  ORGANIZATION_OWNERSHIP_CHANGED: 'ORGANIZATION_OWNERSHIP_CHANGED',
  ORGANIZATION_MEMBER_CHANGED: 'ORGANIZATION_MEMBER_CHANGED',
});

export function isOrganizationAuditEventName(value) {
  return Object.values(OrganizationAuditEvent).includes(value) && /^[A-Z][A-Z0-9_]+$/.test(value);
}
